baseURL = "http://blog.zhoulouzi.com/"
languageCode = "en-us"
defaultContentLanguage = "zh-cn"
title = "Blog zhoulouzi"
theme = "hugo-tranquilpeak-theme"
disqusShortname = "blog-zhoulouzi-com"
googleAnalytics = UA-110602463-1
paginate = 7
canonifyurls = true
publishDir = "docs"

[permalinks]
  post = "/:year/:month/:slug/"

[taxonomies]
  tag = "tags"
  category = "categories"
  archive = "archives"

[author]
  name = "zhoulouzi"
  bio = "KEEP FOCUS AND CARRY ON"
  job = "Dev ops"
  location = "China Beijing"
  gravatarEmail = "zhoulouzi@hotmail.com"
  twitter = "zhoulouzi"

# Menu Configuration
[[menu.main]]
  weight = 1
  identifier = "home"
  name = "Home"
  pre = "<i class=\"sidebar-button-icon fa fa-lg fa-home\"></i>"
  url = "/"
[[menu.main]]
  weight = 2
  identifier = "categories"
  name = "Categories"
  pre = "<i class=\"sidebar-button-icon fa fa-lg fa-bookmark\"></i>"
  url = "/categories"
[[menu.main]]
  weight = 3
  identifier = "tags"
  name = "Tags"
  pre = "<i class=\"sidebar-button-icon fa fa-lg fa-tags\"></i>"
  url = "/tags"
[[menu.main]]
  weight = 4
  identifier = "archives"
  name = "Archives"
  pre = "<i class=\"sidebar-button-icon fa fa-lg fa-archive\"></i>"
  url = "/archives"
[[menu.links]]
  weight = 1
  identifier = "github"
  name = "GitHub"
  pre = "<i class=\"sidebar-button-icon fa fa-lg fa-github\"></i>"
  url = "https://github.com/zhoulouzi"
[[menu.links]]
  weight = 2
  identifier = "twitter"
  name = "twitter"
  pre = "<i class=\"sidebar-button-icon fa fa-lg fa-twitter\"></i>"
  url = "https://twitter.com/zhoulouzi"

[params]
  # Global keywords configuration. Following keywords will be add to every pages
  keywords = ["zhoulouzi"]
  syntaxHighlighter = "highligth.js"
  clearReading = true

  hierarchicalCategories = true

  description = "blogs"
  sidebarBehavior = 2
  coverImage = "http://opiq5jspn.bkt.clouddn.com/ChMkJ1f8ljWIBAmcAA-gWT6p-0oAAWzegGSHVwAD6Bx012.jpg"

  imageGallery = true
  thumbnailImage = true
  thumbnailImagePosition = "right"
  autoThumbnailImage = true

  swapPaginator = true
  [[params.sharingOptions]]
    name = "Twitter"
    icon = "fa-twitter"
    url = "https://twitter.com/intent/tweet?text=%s"

  [params.header.rightLink]
    class = ""
    icon = ""
    url = "/#about"
